Testing workflow

diff --git a/.github/workflows/qa-deploy.yml b/.github/workflows/qa-deploy.yml
--- a/.github/workflows/qa-deploy.yml
+++ b/.github/workflows/qa-deploy.yml
@@ -153,13 +153,6 @@ jobs:
           echo "NAME_LOWER: $NAME_LOWER"
           echo "::set-output name=name_lower::$NAME_LOWER"
 
-      - name: Checkout custom AZ KV action
-        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
-        with:
-          repository: joseph-flinn/get-keyvault-secrets
-          ref: 07b54e7df161105193fb62e3b594e496377f2e84
-          path: ./.github/actions/get-keyvault-secrets
-
       - name: Download aritifacts
         uses: actions/download-artifact@158ca71f7c614ae705e79f25522ef4658df18253
         with:
@@ -172,171 +165,180 @@ jobs:
 
       - name: Retrieve secrets
         id: retrieve-secrets
-        uses: ./.github/actions/get-keyvault-secrets
+        uses: Azure/get-keyvault-secrets@80ccd3fafe5662407cc2e55f202ee34bfff8c403
         with:
           keyvault: "bitwarden-qa-kv"
-          secrets: "appservices-${{ steps.setup.outputs.name_lower }}-webapp-name:webapp-name"
+          secrets: "appservices-${{ steps.setup.outputs.name_lower }}-webapp-name, 
+                    appservices-${{ steps.setup.outputs.name_lower }}-webapp-publish-profile"
 
-      - name: Deploy App
-        uses: azure/webapps-deploy@798e43877120eda6a2a690a4f212c545e586ae31
-        with:
-          app-name: ${{ steps.retrieve-secrets.outputs.webapp-name }} 
-          slot-name: "staging"
-          package: ./${{ matrix.name }}.zip
-
-
-  swap-identity:
-    runs-on: ubuntu-latest
-    needs: deploy
-    steps:
-      - name: Checkout custom AZ KV action
-        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
-        with:
-          repository: joseph-flinn/get-keyvault-secrets
-          ref: 07b54e7df161105193fb62e3b594e496377f2e84
-          path: ./.github/actions/get-keyvault-secrets
-
-      - name: Login to Azure
-        uses: Azure/login@77f1b2e3fb80c0e8645114159d17008b8a2e475a
-        with:
-          creds: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}
-
-      - name: Retrieve secrets
-        id: retrieve-secrets
-        uses: ./.github/actions/get-keyvault-secrets
-        with:
-          keyvault: "bitwarden-qa-kv"
-          secrets: "appservices-identity-webapp-name:IDENTITY_WEBAPP_NAME"
-
-      - name: Start staging slot
-        run: az webapp start --name $IDENTITY_WEBAPP_NAME --resource-group bitwarden-qa --slot staging
-
-      - name: Make sure staging endpoint is alive
+      - name: Test outputs
+        env:
+          TEST_VAR: ${{ format('steps.retrieve-secrets.outputs.appservices-{0}-webapp-name', steps.setup.outputs.name_lower) }}
         run: |
-          SUCCESS="no"
-          while read OUTPUT
-          do
-            STATUS=$( curl -is https://$IDENTITY_WEBAPP_NAME-staging.azurewebsites.net/.well-known/openid-configuration/jwks | head -1 )
-            if [[ "$STATUS" == *"200 OK"* ]]; then
-              echo "It is live!"
-              SUCCESS="yes"
-              break
-            fi
-            echo -e "STAUS=$STATUS\nRetrying: $OUTPUT"
-            sleep 4;
-          done < <(seq 15)
+          echo "**********"
+          echo "$TEST_VAR"
+          echo "**********"
 
-          if [[ "$SUCCESS" == "no" ]]; then
-            exit 1
-          fi
+      # - name: Deploy App
+      #   uses: azure/webapps-deploy@798e43877120eda6a2a690a4f212c545e586ae31
+      #   with:
+      #     app-name: ${{ format('steps.retrieve-secrets.outputs.appservices-{0}-webapp-name', steps.setup.outputs.name_lower) }} 
+      #     slot-name: "staging"
+      #     package: ./${{ matrix.name }}.zip
+
+
+  # swap-identity:
+  #   runs-on: ubuntu-latest
+  #   needs: deploy
+  #   steps:
+  #     - name: Checkout custom AZ KV action
+  #       uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
+  #       with:
+  #         repository: joseph-flinn/get-keyvault-secrets
+  #         ref: 07b54e7df161105193fb62e3b594e496377f2e84
+  #         path: ./.github/actions/get-keyvault-secrets
+
+  #     - name: Login to Azure
+  #       uses: Azure/login@77f1b2e3fb80c0e8645114159d17008b8a2e475a
+  #       with:
+  #         creds: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}
+
+  #     - name: Retrieve secrets
+  #       id: retrieve-secrets
+  #       uses: ./.github/actions/get-keyvault-secrets
+  #       with:
+  #         keyvault: "bitwarden-qa-kv"
+  #         secrets: "appservices-identity-webapp-name:IDENTITY_WEBAPP_NAME"
+
+  #     - name: Start staging slot
+  #       run: az webapp start --name $IDENTITY_WEBAPP_NAME --resource-group bitwarden-qa --slot staging
+
+  #     - name: Make sure staging endpoint is alive
+  #       run: |
+  #         SUCCESS="no"
+  #         while read OUTPUT
+  #         do
+  #           STATUS=$( curl -is https://$IDENTITY_WEBAPP_NAME-staging.azurewebsites.net/.well-known/openid-configuration/jwks | head -1 )
+  #           if [[ "$STATUS" == *"200 OK"* ]]; then
+  #             echo "It is live!"
+  #             SUCCESS="yes"
+  #             break
+  #           fi
+  #           echo -e "STAUS=$STATUS\nRetrying: $OUTPUT"
+  #           sleep 4;
+  #         done < <(seq 15)
+
+  #         if [[ "$SUCCESS" == "no" ]]; then
+  #           exit 1
+  #         fi
             
 
-      - name: Swap Identity
-        run: az webapp deployment slot swap -g bitwarden-qa -n $IDENTITY_WEBAPP_NAME --slot staging --target-slot production
+  #     - name: Swap Identity
+  #       run: az webapp deployment slot swap -g bitwarden-qa -n $IDENTITY_WEBAPP_NAME --slot staging --target-slot production
 
-      - name: Stop staging slot
-        run: az webapp stop --name $IDENTITY_WEBAPP_NAME --resource-group bitwarden-qa --slot staging
-
-
-  swap-slots:
-    runs-on: ubuntu-latest
-    needs: swap-identity
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - name: Api
-          - name: Billing
-          - name: Events
-          - name: Sso
-          - name: Portal
-    steps:
-      - name: Setup
-        id: setup
-        run: |
-          NAME_LOWER=$(echo "${{ matrix.name }}" | awk '{print tolower($0)}')
-          echo "::set-output name=name_lower::$NAME_LOWER"
-
-      - name: Checkout custom AZ KV action
-        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
-        with:
-          repository: joseph-flinn/get-keyvault-secrets
-          ref: 07b54e7df161105193fb62e3b594e496377f2e84
-          path: ./.github/actions/get-keyvault-secrets
-
-      - name: Login to Azure
-        uses: Azure/login@77f1b2e3fb80c0e8645114159d17008b8a2e475a
-        with:
-          creds: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}
-
-      - name: Retrieve secrets
-        id: retrieve-secrets
-        uses: ./.github/actions/get-keyvault-secrets
-        with:
-          keyvault: "bitwarden-qa-kv"
-          secrets: "appservices-${{ steps.setup.outputs.name_lower }}-webapp-name:WEBAPP_NAME"
-
-      - name: Start staging slot
-        run: az webapp start --name $WEBAPP_NAME --resource-group bitwarden-qa --slot staging
-
-      - name: Make sure staging endpoint is alive
-        run: |
-          SUCCESS="no"
-          while read OUTPUT
-          do
-            STATUS=$( curl -is https://$WEBAPP_NAME-staging.azurewebsites.net/alive | head -1 )
-            if [[ "$STATUS" == *"200 OK"* ]]; then
-              echo "It is live!"
-              SUCCESS="yes"
-              break
-            fi
-            echo -e "STAUS=$STATUS\nRetrying: $OUTPUT"
-            sleep 4;
-          done < <(seq 15)
-
-          if [[ "$SUCCESS" == "no" ]]; then
-            exit 1
-          fi
-
-      - name: Swap slots
-        run: az webapp deployment slot swap -g bitwarden-qa -n $WEBAPP_NAME --slot staging --target-slot production
-
-      - name: Stop staging slot
-        run: az webapp stop --name $WEBAPP_NAME --resource-group bitwarden-qa --slot staging
+  #     - name: Stop staging slot
+  #       run: az webapp stop --name $IDENTITY_WEBAPP_NAME --resource-group bitwarden-qa --slot staging
 
 
-  swap-admin:
-    runs-on: ubuntu-latest
-    needs: swap-slots
-    steps:
-      - name: Checkout custom AZ KV action
-        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
-        with:
-          repository: joseph-flinn/get-keyvault-secrets
-          ref: 07b54e7df161105193fb62e3b594e496377f2e84
-          path: ./.github/actions/get-keyvault-secrets
+  # swap-slots:
+  #   runs-on: ubuntu-latest
+  #   needs: swap-identity
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #         - name: Api
+  #         - name: Billing
+  #         - name: Events
+  #         - name: Sso
+  #         - name: Portal
+  #   steps:
+  #     - name: Setup
+  #       id: setup
+  #       run: |
+  #         NAME_LOWER=$(echo "${{ matrix.name }}" | awk '{print tolower($0)}')
+  #         echo "::set-output name=name_lower::$NAME_LOWER"
 
-      - name: Login to Azure
-        uses: Azure/login@77f1b2e3fb80c0e8645114159d17008b8a2e475a
-        with:
-          creds: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}
+  #     - name: Checkout custom AZ KV action
+  #       uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
+  #       with:
+  #         repository: joseph-flinn/get-keyvault-secrets
+  #         ref: 07b54e7df161105193fb62e3b594e496377f2e84
+  #         path: ./.github/actions/get-keyvault-secrets
 
-      - name: Retrieve secrets
-        id: retrieve-secrets
-        uses: ./.github/actions/get-keyvault-secrets
-        with:
-          keyvault: "bitwarden-qa-kv"
-          secrets: "appservices-admin-webapp-name:ADMIN_WEBAPP_NAME"
+  #     - name: Login to Azure
+  #       uses: Azure/login@77f1b2e3fb80c0e8645114159d17008b8a2e475a
+  #       with:
+  #         creds: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}
 
-      - name: Start staging slot
-        run: az webapp start --name $ADMIN_WEBAPP_NAME --resource-group bitwarden-qa --slot staging
+  #     - name: Retrieve secrets
+  #       id: retrieve-secrets
+  #       uses: ./.github/actions/get-keyvault-secrets
+  #       with:
+  #         keyvault: "bitwarden-qa-kv"
+  #         secrets: "appservices-${{ steps.setup.outputs.name_lower }}-webapp-name:WEBAPP_NAME"
 
-      - name: Make sure staging endpoint is alive
-        run: |
-          sleep 60  # I don't think the admin portal has an alive endpoint
+  #     - name: Start staging slot
+  #       run: az webapp start --name $WEBAPP_NAME --resource-group bitwarden-qa --slot staging
 
-      - name: Swap Admin
-        run: az webapp deployment slot swap -g bitwarden-qa -n $ADMIN_WEBAPP_NAME --slot staging --target-slot production
+  #     - name: Make sure staging endpoint is alive
+  #       run: |
+  #         SUCCESS="no"
+  #         while read OUTPUT
+  #         do
+  #           STATUS=$( curl -is https://$WEBAPP_NAME-staging.azurewebsites.net/alive | head -1 )
+  #           if [[ "$STATUS" == *"200 OK"* ]]; then
+  #             echo "It is live!"
+  #             SUCCESS="yes"
+  #             break
+  #           fi
+  #           echo -e "STAUS=$STATUS\nRetrying: $OUTPUT"
+  #           sleep 4;
+  #         done < <(seq 15)
 
-      - name: Stop staging slot
-        run: az webapp stop --name $ADMIN_WEBAPP_NAME --resource-group bitwarden-qa --slot staging
+  #         if [[ "$SUCCESS" == "no" ]]; then
+  #           exit 1
+  #         fi
+
+  #     - name: Swap slots
+  #       run: az webapp deployment slot swap -g bitwarden-qa -n $WEBAPP_NAME --slot staging --target-slot production
+
+  #     - name: Stop staging slot
+  #       run: az webapp stop --name $WEBAPP_NAME --resource-group bitwarden-qa --slot staging
+
+
+  # swap-admin:
+  #   runs-on: ubuntu-latest
+  #   needs: swap-slots
+  #   steps:
+  #     - name: Checkout custom AZ KV action
+  #       uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
+  #       with:
+  #         repository: joseph-flinn/get-keyvault-secrets
+  #         ref: 07b54e7df161105193fb62e3b594e496377f2e84
+  #         path: ./.github/actions/get-keyvault-secrets
+
+  #     - name: Login to Azure
+  #       uses: Azure/login@77f1b2e3fb80c0e8645114159d17008b8a2e475a
+  #       with:
+  #         creds: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}
+
+  #     - name: Retrieve secrets
+  #       id: retrieve-secrets
+  #       uses: ./.github/actions/get-keyvault-secrets
+  #       with:
+  #         keyvault: "bitwarden-qa-kv"
+  #         secrets: "appservices-admin-webapp-name:ADMIN_WEBAPP_NAME"
+
+  #     - name: Start staging slot
+  #       run: az webapp start --name $ADMIN_WEBAPP_NAME --resource-group bitwarden-qa --slot staging
+
+  #     - name: Make sure staging endpoint is alive
+  #       run: |
+  #         sleep 60  # I don't think the admin portal has an alive endpoint
+
+  #     - name: Swap Admin
+  #       run: az webapp deployment slot swap -g bitwarden-qa -n $ADMIN_WEBAPP_NAME --slot staging --target-slot production
+
+  #     - name: Stop staging slot
+  #       run: az webapp stop --name $ADMIN_WEBAPP_NAME --resource-group bitwarden-qa --slot staging
